### ISSUE TITLE
KeyError: 'from_yaml' while trying to test the pre-trained model

### ISSUE THREAD

**Issue by maky-hnou** [zhou13/lcnn#11]
I want to test the pre-trained model. These are the steps that I've followed:  

1. I've cloned the project  
2. I've downloaded the pre-trained model  
3. I've created the src folder and put an image in it  
4. I've created an empty dst folder  
So the cloned repository tree is as follows:  
```
.
├── 190418-201834-f8934c6-lr4d10-312k.pth.tar
├── config
│   └── wireframe.yaml
├── dataset
│   ├── wireframe.py
│   └── york.py
├── dst
│   └── mat
├── eval-APH.py
├── eval-mAPJ.py
├── eval-sAP.py
├── figs
│   ├── 000452_AFM.png
│   ├── 000452_GT.png
│   ├── 000452_LCNN.png
│   ├── 000452_LSD.png
│   ├── 000452_WF.png
│   ├── PR-APH.svg
│   └── PR-sAP10.svg
├── lcnn
│   ├── box.py
│   ├── config.py
│   ├── datasets.py
│   ├── __init__.py
│   ├── metric.py
│   ├── models
│   │   ├── hourglass_pose.py
│   │   ├── __init__.py
│   │   ├── line_vectorizer.py
│   │   ├── multitask_learner.py
│   │   └── __pycache__
│   │       ├── hourglass_pose.cpython-36.pyc
│   │       ├── __init__.cpython-36.pyc
│   │       ├── line_vectorizer.cpython-36.pyc
│   │       └── multitask_learner.cpython-36.pyc
│   ├── __pycache__
│   │   ├── box.cpython-36.pyc
│   │   ├── config.cpython-36.pyc
│   │   ├── datasets.cpython-36.pyc
│   │   ├── __init__.cpython-36.pyc
│   │   ├── trainer.cpython-36.pyc
│   │   └── utils.cpython-36.pyc
│   ├── trainer.py
│   └── utils.py
├── LICENSE
├── matlab
│   ├── correspondPixels.mexa64
│   ├── correspondPixels.mexmaci64
│   └── eval_release.m
├── misc
│   ├── draw-wireframe.py
│   ├── gdrive-download.sh
│   ├── lsd.py
│   └── plot-sAP.py
├── post.py
├── process.py
├── README.md
├── src
│   └── x8.jpg
└── train.py  

```
Then I run this command `python process.py --plot config/wireframe.yaml 190418-201834-f8934c6-lr4d10-312k.pth.tar src/ dst/` (as described in the [README.md file](https://github.com/zhou13/lcnn#pre-trained-models).  
But I got this error:  
```
Traceback (most recent call last):
  File "/home/nti/Octo/lcnn/lcnn/box.py", line 412, in __getitem__
    value = super(Box, self).__getitem__(item)
KeyError: 'from_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nti/Octo/lcnn/lcnn/box.py", line 492, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/home/nti/Octo/lcnn/lcnn/box.py", line 419, in __getitem__
    raise BoxKeyError(str(err))
lcnn.box.BoxKeyError: "'from_yaml'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nti/Octo/lcnn/lcnn/box.py", line 494, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'Box' object has no attribute 'from_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 133, in <module>
    main()
  File "process.py", line 46, in main
    C.update(C.from_yaml(filename=config_file))
  File "/home/nti/Octo/lcnn/lcnn/box.py", line 511, in __getattr__
    raise BoxKeyError(str(err))
lcnn.box.BoxKeyError: "'Box' object has no attribute 'from_yaml'"

```  
How to fix it?  
Thank you in advance

**Comment by zhou13** [comment]
Do you have `pyyaml` installed?

**Comment by maky-hnou** [comment]
Thank you, that solved the problem. It was my mistake to not follow the installation steps.  
May be it would better to add a `requirements.txt` file with all the needed packages.

**Comment by Jiolen** [comment]
Hi zhou13,
I also want to test a picture with your pre-trained model, and then I follow the method of the questioner mentioned above, but I don't continue to execute in this sentence（loader = torch.utils.data.DataLoader(）），which throws a ‘nvalid： 0’；  I put the test picture to src directory. I guess it should be my args ["<image-dir>"] probelm? However, i cannot locate specific problems.
What is the reason，could u help me，looking forward to your answer, thank you

**Comment by Jiolen** [comment]
another problem, because of network reasons, I have been unable to download the data on google drive. Can you show me an annotated file in json format? I want to look at the specific annotation format. Or what labeling software did you use?  thanks again
