### ISSUE TITLE
No such file or directory: 'tensorboard'

### ISSUE THREAD

**Issue by jwngo** [zhou13/lcnn#26]
Hi, after following the steps that you have provided for installation on a google cloud VM, I am receiving the following error after running 
`python ./train.py -d 0 --identifier baseline config/wireframe.yaml`

```
Traceback (most recent call last):
File "./train.py", line 185, in <module>
    main()
File "./train.py", line 162, in main
    trainer = lcnn.trainer.Trainer(  
File "/home/jiawei/lcnn/lcnn/trainer.py", line 40, in __init__
    self.run_tensorboard()  
File "/home/jiawei/lcnn/lcnn/trainer.py", line 60, in run_tensorboard
    p = subprocess.Popen( 
File "/home/jiawei/miniconda3/envs/lcnn/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,  
File "/home/jiawei/miniconda3/envs/lcnn/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard'


```
Would you have any idea how to fix this? I've tried reinstalling conda and searching online for solutions.

**Comment by jwngo** [comment]
Solved by running 
`conda install -c conda-forge tensorboard
`
